#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Please run 1-install_nginx_web_server first."
    exit 1
fi

# Define the redirection destination URL
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Create a backup of the default Nginx configuration
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Use sed to configure redirection in the Nginx configuration
sed -i '/server_name _;/a \\n\tlocation /redir
