#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom configuration file for Nginx
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/extra_headers.conf

# Restart Nginx to apply changes
sudo service nginx restart
