#!/usr/bin/env bash
# 1. Install load balancer

# Update and upgrade the system
sudo apt-get update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
echo "
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

backend lb-backend
    mode http
    balance roundrobin
    server 444376-web-01 54.87.214.4:80 check
    server 444376-web-02 52.3.255.28:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restar
